name: yuvify_website
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.11.0

dependencies:
  flutter:
    sdk: flutter
  
  flutter_web_plugins:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^8.0.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  assets:
    - lib/assets/logo.png
    - lib/assets/logo_transparent.png
    - lib/assets/mind_map.png
    - lib/assets/plan_notes.png
    - lib/assets/logo_text.png
    - lib/assets/instagram.png
    - lib/assets/linkedin.png
